version: 2
updates:
  # 1. Python Libraries Management in demo-app
  - package-ecosystem: "pip"
    directory: "/demo-app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"

  # 2. Docker images management in Dockerfile and Docker Compose
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"

  # Add configuration for scanning Dockerfile at child directory
  - package-ecosystem: "docker"
    directory: "/demo-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/elasticsearch"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/kibana"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/logstash"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/beats/fleet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/beats/agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"

  # 3. GitHub Actions workflows management
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(actions)"
