version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}
    container_name: es-node
    environment:
      - node.name=es-node
      - cluster.name=crypto-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - TZ=UTC

      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.ml.enabled=false
      - ingest.geoip.downloader.enabled=false

      # Cho phép gọi API từ trình duyệt (React/Vue/Postman)
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:9200"
    networks:
      - elastic-net
    restart: unless-stopped
    # [NEW] Xoay vòng log để tránh đầy ổ cứng Mac
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_STACK_VERSION}
    container_name: kibana
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=http://es-node:9200
      - ELASTICSEARCH_REQUESTTIMEOUT=90000
      - MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true
      - TELEMETRY_ENABLED=false
      - TZ=UTC

      # Turn off unnecessary feature
      - XPACK_SECURITY_ENABLED=false
      - XPACK_REPORTING_ROLES_ENABLED=false
      - XPACK_ML_ENABLED=false
      - XPACK_ELASTIC_ASSISTANT_ENABLED=false
      - XPACK_OBSERVABILITY_AIASSISTANT_ENABLED=false
      - XPACK_FLEET_ENABLED=false
      - XPACK_FLEET_AGENTS_ENABLED=false
      - XPACK_APM_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_GRAPH_ENABLED=false
      - XPACK_INFRA_SOURCES_DEFAULT_METRIC_ALIAS=metricbeat-*
      - XPACK_INFRA_SOURCES_DEFAULT_LOG_ALIAS=filebeat-*
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - elastic-net
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601/api/status | grep -q 'HTTP/1.1 200 OK' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

#  # Quản trị viên ES - Nhẹ và trực quan
#  cerebro:
#    image: lmenezes/cerebro:0.9.4
#    container_name: cerebro
#    ports:
#      - "9000:9000"
#    networks:
#      - elastic-net
#    restart: unless-stopped
#    command:
#      - -Dhosts.0.host=http://es-node:9200
#      - -Dhosts.0.name=Crypto-Cluster
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"

volumes:
  es_data:
  kibana_data:

networks:
  elastic-net:
    driver: bridge