version: '3'
services:
  # 1. Cái "Đầu đĩa" (Database)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: es-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Tắt bảo mật để đỡ phải nhập pass khi dev
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # 2. Cái "Màn hình" (UI)
  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.1
    container_name: kibana-ui
    environment:
      - ELASTICSEARCH_HOSTS=http://es-node:9200 # Trỏ vào container ES ở trên
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data: