# This file configuration is suitable for production environment, adjust accordingly to what you need

cluster.name: elastic-cluster
node.name: es-node

# Cấu hình Single-node (Quan trọng)
discovery.type: single-node

# Mạng
network.host: 0.0.0.0
http.port: 9200

# Tắt Swap (Cần đi kèm ulimits trong docker-compose)
bootstrap.memory_lock: true

# Tắt Security (Dev mode)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false