# This file configuration is suitable for production environment, adjust accordingly to what you need

server.name: kibana
server.host: "0.0.0.0" # Mở cửa cho máy host truy cập
server.port: 5601

# Kết nối tới ES
elasticsearch.hosts: [ "http://es-node:9200" ]

# Đồng bộ tắt Security
xpack.security.enabled: false

# Tối ưu
telemetry.enabled: false
monitoring.ui.container.elasticsearch.enabled: true